import esbuild from "esbuild";
import process from "process";
import path from "node:path";
import { copyFileSync, existsSync } from "node:fs";

const prod = process.argv[2] === "production";
const PLUGIN_ROOT = path.resolve(".");

const banner = `/*
 * THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
 * Source: obsidian-plugin-translator
 */
`;

// ── 样式表：构建时从源码根复制到插件根目录（Obsidian 插件约定 styles.css 在根，随插件分发）──
if (!existsSync("styles.css")) {
	throw new Error("Missing styles.css at project root");
}
copyFileSync("styles.css", path.join(PLUGIN_ROOT, "styles.css"));

// ── 运行时 WASM 资产：构建时从 node_modules 拷贝到插件根目录，随插件分发 ──
const copyWasm = (src, name) => {
	if (!existsSync(src)) {
		throw new Error(`Missing WASM asset: ${src}`);
	}
	copyFileSync(src, path.join(PLUGIN_ROOT, name));
	console.log(`✓ copied ${name}`);
};
copyWasm("./node_modules/sql.js/dist/sql-wasm.wasm", "sql-wasm.wasm");
copyWasm(
	"./node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.jsep.wasm",
	"ort-wasm-simd-threaded.jsep.wasm",
);

// ── Worker bundle 路径（中间产物，prod 后删除，源码内联进 main.js）──
const WORKER_BUNDLE_PATH = path.join(PLUGIN_ROOT, "embedding-worker.bundle.js");

// ── Electron worker 里的 process.release.name === "node" 会触发 transformers
//    env.js 的 Node 检测，破坏模型加载。在 worker bundle 开头打补丁强制走浏览器路径。──
const WORKER_NODE_PROCESS_PATCH = `(function(){
  try {
    var p = typeof process !== "undefined" ? process : null;
    if (p && p.release && p.release.name === "node") {
      Object.defineProperty(p.release, "name", { value: "electron-worker", configurable: true, enumerable: true });
    }
  } catch (_e) {}
})();`;

// ── Stub 原生模块：sharp（transformers node 构建 import 但文本 embedding 不用）──
const nativeStubPlugin = {
	name: "native-stub",
	setup(build) {
		for (const mod of ["sharp"]) {
			build.onResolve({ filter: new RegExp(`^${mod}$`) }, () => ({
				path: mod,
				namespace: "native-stub",
			}));
		}
		build.onLoad({ filter: /.*/, namespace: "native-stub" }, (args) => ({
			contents: `// stubbed native module: ${args.path}\nmodule.exports = {};`,
			loader: "js",
		}));
	},
};

// ── sql.js Emscripten 输出的 node:fs / node:crypto 死代码引用打 stub ──
const stripNodeBuiltinsPlugin = {
	name: "strip-node-builtins",
	setup(build) {
		build.onResolve({ filter: /^node:(fs|crypto)$/ }, (args) => ({
			path: args.path,
			namespace: "node-builtin-stub",
		}));
		build.onLoad({ filter: /.*/, namespace: "node-builtin-stub" }, (args) => ({
			contents: `// ${args.path} is unreachable in Obsidian renderer; stubbed.\nmodule.exports = {};`,
			loader: "js",
		}));
	},
};

// 注（PERF-3）：worker bundle 不再内联进 main.js，而是作为独立文件
// embedding-worker.bundle.js 随插件分发，运行时由 app 层经 adapter 读入再 Blob 实例化。
// 纯关键词用户因此不再为内联 worker 源码付出 main.js 体积/解析成本（原 main.js 可缩减一半以上）。

// 注（PERF micro）：主 bundle 曾配置 transformers/ort 别名，但主线程并无任何
// @huggingface/transformers / onnxruntime import（全部跑在 Step 1 的 worker bundle 里），
// 属死配置，已移除。Step 1 的 worker alias 仍保留（embedding-worker.ts 真正用到）。

// ════════════════════════════════════════════════════════════════════════════
// Step 1：打包 Embedding Worker（transformers + onnxruntime 全在 worker 里跑）
// ════════════════════════════════════════════════════════════════════════════
await esbuild.build({
	entryPoints: ["src/semantic/workers/embedding-worker.ts"],
	bundle: true,
	format: "iife",
	platform: "browser",
	target: "es2020",
	banner: { js: WORKER_NODE_PROCESS_PATCH },
	logLevel: "info",
	minify: true,
	sourcemap: false,
	loader: { ".wasm": "binary" },
	tsconfig: "tsconfig.json",
	alias: {
		"@huggingface/transformers":
			"./node_modules/@huggingface/transformers/dist/transformers.web.js",
		"onnxruntime-web": "./node_modules/onnxruntime-web/dist/ort.webgpu.bundle.min.mjs",
		"onnxruntime-web/webgpu": "./node_modules/onnxruntime-web/dist/ort.webgpu.bundle.min.mjs",
	},
	plugins: [nativeStubPlugin],
	outfile: WORKER_BUNDLE_PATH,
	define: { "process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development") },
});

// ════════════════════════════════════════════════════════════════════════════
// Step 2：主插件 bundle。worker 源码内联，sql.js/transformers 打包进 main.js，
//          node:fs/node:crypto/sharp 打 stub。
//          注意：这里用一次性 esbuild.build 而非 context.rebuild。
//          context.rebuild 在「同进程先 esbuild.build 再建 context」的场景下，
//          会错误判定 main.js 内容未变化而跳过写盘（outputFiles 返回 none），
//          导致 main.js 停留在旧版本。一次性 build 无此缓存问题。
// ════════════════════════════════════════════════════════════════════════════
await esbuild.build({
	banner: { js: banner },
	entryPoints: ["src/app/main.ts"],
	bundle: true,
	loader: { ".wasm": "binary" },
	tsconfig: "tsconfig.json",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
	],
	format: "cjs",
	target: "es2020",
	platform: "node",
	logLevel: "info",
	minify: prod,
	sourcemap: prod ? "external" : "inline",
	treeShaking: true,
	outfile: path.join(PLUGIN_ROOT, "main.js"),
	plugins: [nativeStubPlugin, stripNodeBuiltinsPlugin],
	define: { "process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development") },
});

// worker bundle 作为独立文件保留（随插件分发，运行时按需读取），不再删除
console.log(`✓ worker bundle 保留为独立文件：${path.basename(WORKER_BUNDLE_PATH)}`);
